obstacle_detector_node:
  ros__parameters:
    # Distanza massima per associare un nuovo rilevamento a un track esistente.
    max_tracking_distance: 0.6

    # Tempo in secondi prima di eliminare un track non più visto.
    track_lifetime: 2.0

    # Orizzonte di predizione in secondi. Aumentato per dare più tempo di reazione al robot lento.
    prediction_horizon: 3.5
    prediction_steps: 7

    kf:
      p: [0.1, 0.1, 10.0, 10.0] # Incertezza iniziale: bassa per la posizione, alta per la velocità.
      r: [0.05, 0.05]           # Rumore di misura: ci fidiamo abbastanza del LiDAR (valori bassi).
      q: [0.01, 0.01, 0.5, 0.5] # Rumore di processo: permettiamo alla velocità di cambiare più rapidamente per seguire le svolte.

