mppi_controller:
  ros__parameters:
    # Usare l'orologio di simulazione
    use_sim_time: true

    # Frame del robot e mappa
    base_frame: "base_link"
    global_frame: "map"

    # Parametri MPPI
    sampling_time: 0.1           # Δt tra rollout (s)
    prediction_horizon: 20       # numero di passi futuri
    num_samples: 200             # numero di rollout
    noise_sigma: [0.2, 0.5]      # varianza del rumore [v, ω]
    lambda: 1.0                  # parametro di “temperatura”

    # Guadagni di costo
    goal_cost_gain: 1.0
    obstacle_cost_gain: 10.0
    effort_cost_gain: 0.1

    # Costmap/ostacoli
    inflation_radius: 0.3
    dynamic_obstacle_predictor: true
