obstacle_detector_node:
  ros__parameters:
    # --- Parametri di Clustering (DBSCAN) ---
    # Distanza massima (epsilon) tra i punti per essere considerati nello stesso vicinato.
    dbscan_eps: 0.5
    # Numero minimo di punti per formare un cluster denso.
    dbscan_min_samples: 4

    # Distanza massima per associare un nuovo rilevamento a un track esistente.
    max_tracking_distance: 0.6

    # Tempo in secondi prima di eliminare un track non più visto.
    track_lifetime: 2.0

    # Orizzonte di predizione in secondi.
    prediction_horizon: 5.0
    prediction_steps: 10

    kf:
      p: [0.1, 0.1, 10.0, 10.0]     # Incertezza iniziale: bassa per la posizione, alta per la velocità.
      r: [0.3, 0.3]                 # Rumore di misura: ci fidiamo abbastanza del LiDAR (valori bassi).
      q: [0.001, 0.001, 0.01, 0.01] # Rumore di processo: permettiamo alla velocità di cambiare più rapidamente per seguire le svolte.

